name: tasbih_app
description: المسبحة الإلكترونية
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vibration: ^1.8.4
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
